# Generated by Django 4.1 on 2024-03-12 05:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('disid', models.AutoField(primary_key=True, serialize=False)),
                ('disname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locid', models.AutoField(primary_key=True, serialize=False)),
                ('locname', models.CharField(max_length=50)),
                ('disid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.district')),
            ],
        ),
        migrations.CreateModel(
            name='tblcategory',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tblequipment',
            fields=[
                ('equipid', models.AutoField(primary_key=True, serialize=False)),
                ('equipname', models.CharField(max_length=50)),
                ('equipphoto', models.ImageField(upload_to='')),
                ('regdate', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=50)),
                ('quantity', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainerid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('trainerphoto', models.ImageField(upload_to='')),
                ('phone', models.BigIntegerField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('regdate', models.DateField(default=datetime.date.today)),
                ('catid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.tblcategory')),
                ('locid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.location')),
            ],
        ),
        migrations.CreateModel(
            name='tblplan',
            fields=[
                ('planid', models.AutoField(primary_key=True, serialize=False)),
                ('planname', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('validity', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('catid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.tblcategory')),
            ],
        ),
    ]
