# Generated by Django 4.1 on 2024-03-12 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0002_alter_trainer_age_alter_trainer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainerassign',
            fields=[
                ('assignid', models.AutoField(primary_key=True, serialize=False)),
                ('trainerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.trainer')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
