# Generated by Django 4.1 on 2024-03-12 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_user_status'),
        ('admin', '0003_trainerassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerassign',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.user'),
        ),
    ]
