# Generated by Django 4.1 on 2024-03-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_alter_trainerassign_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('timeid', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
