# Generated by Django 4.1 on 2024-03-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='meredium',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
