# Generated by Django 4.1 on 2024-03-13 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_user_loginid'),
        ('admin', '0006_time_meredium'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='loginid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.login'),
        ),
        migrations.AddField(
            model_name='trainerassign',
            name='loginid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.login'),
        ),
    ]
