# Generated by Django 4.1 on 2024-03-13 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0007_trainer_loginid_trainerassign_loginid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerassign',
            name='loginid',
        ),
    ]
