# Generated by Django 4.1 on 2024-05-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_user_loginid'),
        ('admin', '0008_remove_trainerassign_loginid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('trainerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.trainer')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.user')),
            ],
        ),
    ]
