# Generated by Django 4.1 on 2024-05-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0009_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='description',
            new_name='feedback',
        ),
    ]
