# Generated by Django 4.1 on 2024-03-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0003_trainerassign'),
        ('guest', '0002_alter_user_age_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planassign',
            fields=[
                ('assignid', models.AutoField(primary_key=True, serialize=False)),
                ('planid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.tblplan')),
                ('trainerid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.trainer')),
                ('userid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.user')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=500)),
                ('assignid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trainer.planassign')),
                ('planid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.tblplan')),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('dietid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('trainerid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.trainer')),
                ('userid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.user')),
            ],
        ),
    ]
