# Generated by Django 4.1 on 2024-03-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planassign',
            old_name='assignid',
            new_name='planassignid',
        ),
    ]
