# Generated by Django 4.1 on 2024-03-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_rename_assignid_planassign_planassignid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='assignid',
        ),
    ]
