# Generated by Django 4.1 on 2024-03-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_user_loginid'),
        ('admin', '0008_remove_trainerassign_loginid'),
        ('trainer', '0003_remove_workout_assignid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planassign',
            new_name='Planrequest',
        ),
    ]
