# Generated by Django 4.1 on 2024-03-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_rename_planassign_planrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrequest',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
