# Generated by Django 4.1 on 2024-03-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_planrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrequest',
            name='time',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
