# Generated by Django 4.1 on 2024-03-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_planrequest_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planrequest',
            name='time',
        ),
    ]
