# Generated by Django 4.1 on 2024-03-25 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_user_loginid'),
        ('admin', '0008_remove_trainerassign_loginid'),
        ('trainer', '0007_remove_planrequest_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timerequest',
            fields=[
                ('timeassignid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('timeid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.time')),
                ('trainerid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.trainer')),
                ('userid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.user')),
            ],
        ),
    ]
