# Generated by Django 4.1 on 2024-04-01 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_timerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diet',
            old_name='name',
            new_name='diet',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='desc',
        ),
    ]
