# Generated by Django 4.1 on 2024-04-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_rename_name_diet_diet_remove_diet_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
