from django.urls import path
from . import views
from .views import ExportExcelUsers

urlpatterns=[
    path('adminindex/', views.index,name='adminindex'),
    path('logout/', views.logout, name='logout'),
    path('districtreg/', views.districtreg, name='districtreg'),
    path('districtview/', views.districtview, name='districtview'),
    path('districtedit/<id>', views.districtedit, name='districtedit'),
    # path('districtdelete/<id>', views.districtdelete, name='districtdelete'),
    path('locationreg/', views.locationreg, name='locationreg'),
    path('filllocation', views.filllocation, name='filllocation'),
    path('locationview/', views.locationview, name='locationview'),
    path('locationedit/<id>', views.locationedit, name='locationedit'),
    # path('locationdelete/<id>', views.locationdelete, name='locationdelete'),
    path('equipmentreg/', views.equipmentreg, name='equipmentreg'),
    path('equipmentview/', views.equipmentview, name='equipmentview'),
    path('equipmentedit/<id>', views.equipmentedit, name='equipmentedit'),
    path('equipmentdelete/<id>', views.equipmentdelete, name='equipmentdelete'),
    path('categoryreg/', views.categoryreg, name='categoryreg'),
    path('categoryview/', views.categoryview, name='categoryview'),
    path('categoryedit/<id>', views.categoryedit, name='categoryedit'),
    path('categorydelete/<id>', views.categorydelete, name='categorydelete'),
    path('planreg', views.planreg, name='planreg'),
    path('planview', views.planview, name='planview'),
    path('planedit/<id>', views.planedit, name='planedit'),
    path('plandelete/<id>', views.plandelete, name='plandelete'),
    path('fillplan', views.fillplan, name='fillplan'),
    path('userview/', views.userview, name='userview'),
    # path('useredit/<id>', views.useredit, name='useredit'),
    path('userdelete/<id>', views.userdelete, name='userdelete'),
    path('trainerreg/', views.trainerreg, name='trainerreg'),
    path('trainerview/', views.trainerview, name='trainerview'),
    path('traineredit/<id>', views.traineredit, name='traineredit'),
    path('trainerdelete/<id>', views.trainerdelete, name='trainerdelete'),
    path('trainerassign/', views.trainerassign, name='trainerassign'),
    path('reassign/', views.reassign, name='reassign'),
    path('reassignedit/<id>', views.reassignedit, name='reassignedit'),
    path('fillassign', views.fillassign, name='fillassign'),
    path('timereg/', views.timereg, name='timereg'),
    path('timeview/', views.timeview, name='timeview'),
    path('filltime', views.filltime, name='filltime'),
    path('timeedit/<id>', views.timeedit, name='timeedit'),
    path('timedelete/<id>', views.timedelete, name='timedelete'),
    path('timedelete/<id>', views.timedelete, name='timedelete'),
    path('reportplan/', views.reportplan, name='reportplan'),
    path('locwiseuser/', views.locwiseuser, name='locwiseuser'),
    path('userlocwise/', views.userlocwise, name='userlocwise'),
    path('filluserloc/', views.filluserloc, name='filluserloc'),
    path('assignedusersxcel/', views.assignedusersxcel, name='assignedusersxcel'),
    path('filltrainersuser/', views.filltrainersuser, name='filltrainersuser'),
    path('usersexcel/', ExportExcelUsers.as_view(), name='usersexcel'),
    path('feedback/', views.feedback, name='feedback'),
]