# Generated by Django 4.1 on 2024-03-12 05:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('loginid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('userphoto', models.ImageField(upload_to='')),
                ('phone', models.BigIntegerField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('regdate', models.DateField(default=datetime.date.today)),
                ('catid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.tblcategory')),
                ('locid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.location')),
            ],
        ),
    ]
