# Generated by Django 4.1 on 2024-03-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loginid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.login'),
        ),
    ]
